name: NightlyTest

on:
  # We want to run the CI when anything is pushed to master.
  # Since master is a protected branch this only happens when a PR is merged.
  # This is a double check in case the PR was stale and had some issues.
  push:
    branches:
      - master
    paths-ignore: # Prevents from running if only docs are updated
      - 'doc/**'
      - '**/*README*'
      - '**.md'
      - '**.rst'
  pull_request:
    paths-ignore: # Prevents from running if only docs are updated
      - 'doc/**'
      - '**/*README*'
      - '**.md'
      - '**.rst'
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *' # daily

env:
  # default compiler for all non-compatibility tests
  MATRIX_EVAL: "CC=gcc-11 && CXX=g++-11"

jobs:
  Run-tests:
    # Prevents from running on forks where no custom runners are available
    if: ${{ github.repository_owner == 'verilog-to-routing' }}

    timeout-minutes: 420

    container: ubuntu:jammy

    runs-on: [self-hosted, Linux, X64]

    strategy:
      fail-fast: false
      matrix:
        include:
          - {test: "vtr_reg_nightly_test1",      cores: "16", options: "",          cmake: "",                                                             extra_pkgs: ""}

    env:
      DEBIAN_FRONTEND: "noninteractive"

    steps:

      # TODO: This runnner is running on a self-hosted CPU. In order to upgrade
      #       to v4, need to upgrade the machine to support node20.
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Setup
      run: stdbuf -i0 -i0 -e0 ./.github/scripts/hostsetup.sh

    - name: Install external libraries
      run: apt install -y ${{ matrix.extra_pkgs }}
      if: ${{ matrix.extra_pkgs }}

    - name: Execute test script
      run: stdbuf -i0 -o0 -e0 ./.github/scripts/run-vtr.sh
      env:
        VPR_NUM_WORKERS: 4
        VTR_TEST: ${{ matrix.test }}
        VTR_TEST_OPTIONS: ${{ matrix.options }}
        VTR_CMAKE_PARAMS: ${{ matrix.cmake }}
        NUM_CORES: ${{ matrix.cores }}


